#!/usr/bin/env python3
"""Collect due-diligence metrics for a list of GitHub / GitLab / local repos.

Metrics produced per repo
-------------------------
1. logical_loc            scc Code column, whole repo
2. non_authored_loc       logical_loc - authored_loc, where authored_loc excludes
                          vendored directories, generated files and minified files
3. duplication_ratio      jscpd percentage / 100 (built-in fallback if jscpd absent)
4. non_merge_commits      git log --no-merges, revert subjects dropped
5. build_test_status      "Builds + test suite passes" / "Builds only" / "Not verified"
                          plus build command and runtime version

Usage
-----
    python3 repo_metrics.py --repos repos.txt --out outputs/run1

    # with real build attempts inside Docker
    python3 repo_metrics.py --repos repos.txt --out outputs/run1 --build-check docker

Input file accepts, one per line (blank lines and # comments ignored):
    owner/repo                          -> GitHub
    https://github.com/owner/repo       -> GitHub
    https://gitlab.com/group/sub/repo   -> GitLab
    git@github.com:owner/repo.git
    /abs/path/to/local/clone
A CSV with a `full_name`, `url`, `repo_url` or `path` column works too, as does a
JSONL file whose objects carry any of those keys.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import fnmatch
import json
import os
import re
import shutil
import subprocess
import sys
import time
import traceback
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple
from workspace_paths import resolve_out  # noqa: E402  (single outputs root)

HERE = Path(__file__).resolve().parent


def default_tokens_file() -> Optional[Path]:
    """Locate the workspace env file without hardcoding a workspace layout.

    DataLabs keeps exactly one env file at its root, so `.env` is preferred;
    the legacy `tokens` name is still honoured for standalone checkouts.
    """
    env = os.environ.get("DATALABS_ENV_FILE") or os.environ.get("DATALABS_TOKENS")
    if env:
        return Path(env)
    for base in (Path.cwd(), *Path.cwd().parents, HERE, *HERE.parents):
        for name in (".env", "tokens"):
            candidate = base / name
            if candidate.is_file():
                return candidate
    return None


def default_clones_dir() -> str:
    """The one DataLabs repo store; falls back to ./clones when standalone."""
    return os.environ.get("DATALABS_CLONES_DIR") or str(_datalabs_clones_root())


def _datalabs_clones_root() -> Path:
    """Walk up for a DataLabs root (marked by datalabs_paths.py) and use its clones/."""
    for base in (Path.cwd(), *Path.cwd().parents, HERE, *HERE.parents):
        if (base / "datalabs_paths.py").is_file():
            return base / "clones"
    return Path.cwd() / "clones"

# Directories excluded from "authored" LOC and from duplication scanning.
DEFAULT_EXCLUDE_DIRS = ["vendor", "node_modules", "dist", "build", "generated", "migrations"]

# Extra vendored directories worth excluding; opt in with --wide-exclude.
WIDE_EXTRA_EXCLUDE_DIRS = [
    "third_party", "thirdparty", "bower_components", "Pods", "Carthage",
    ".yarn", "site-packages", "target", "out", ".next", ".nuxt", "coverage",
]

# Languages scc counts as "Code" that a reviewer would not call source code.
# Matches skills/dataset-repo-metrics NON_CODE_LANGUAGES so both tools agree,
# plus WSDL, which shows up in legacy PHP corpora.
# Used ONLY to derive the additive `code_loc` column. `logical_loc` is always
# the unmodified spec figure and is never affected by this set.
DATA_LANGUAGES = {
    "JSON", "Plain Text", "XML", "Markdown", "CSV", "Text", "Properties File",
    "SVG", "HTML", "CSS", "LESS", "Sass", "SCSS", "YAML", "TOML",
    "Web Services Description Language",
}

SOURCE_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".kt", ".go", ".rb", ".php",
    ".cs", ".c", ".h", ".cc", ".cpp", ".hpp", ".m", ".mm", ".swift", ".rs",
    ".scala", ".sh", ".sql", ".vue", ".dart", ".ex", ".exs", ".pl", ".r",
}

AUTOGEN_HEADER_MARKERS = (
    "do not edit", "auto-generated", "autogenerated", "@generated",
    "<auto-generated", "code generated by", "this file was generated",
)
AUTOGEN_FILE_PATTERNS = (
    "*_generated.*", "*.generated.*", "*_pb2.py", "*_pb2_grpc.py", "*.pb.go",
    "*.pb.cc", "*.pb.h", "*.min.js", "*.min.css", "*.bundle.js", "*.g.dart",
    "*.designer.cs",
)

# Never scanned for duplication. scc already skips these because it honours
# .gitignore; the duplication scanners do not, so they need the list explicitly.
ALWAYS_SKIP_DIRS = {
    ".git", ".hg", ".svn", ".venv", "venv", "env", ".env", ".tox", ".nox",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".gradle",
    ".terraform", ".idea", ".vscode", "site-packages", ".cache",
}

_print_lock_stderr = sys.stderr


def log(msg: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", file=_print_lock_stderr, flush=True)


# ── process helpers ──────────────────────────────────────────────────────────

class CmdResult:
    __slots__ = ("code", "out", "err", "timed_out", "cmd")

    def __init__(self, cmd: Sequence[str], code: int, out: str, err: str, timed_out: bool):
        self.cmd = list(cmd)
        self.code = code
        self.out = out
        self.err = err
        self.timed_out = timed_out

    @property
    def ok(self) -> bool:
        return self.code == 0 and not self.timed_out

    def tail(self, n: int = 800) -> str:
        return ((self.err or self.out) or "").strip()[-n:]


def run(cmd: Sequence[str], cwd: Optional[Path] = None, timeout: int = 900,
        env: Optional[Dict[str, str]] = None) -> CmdResult:
    try:
        proc = subprocess.run(
            list(cmd),
            cwd=str(cwd) if cwd else None,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
        )
        return CmdResult(cmd, proc.returncode, proc.stdout or "", proc.stderr or "", False)
    except subprocess.TimeoutExpired as exc:
        out = exc.stdout.decode() if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        err = exc.stderr.decode() if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return CmdResult(cmd, 124, out, err + f"\n[timeout after {timeout}s]", True)
    except FileNotFoundError as exc:
        return CmdResult(cmd, 127, "", str(exc), False)


# ── tool discovery ───────────────────────────────────────────────────────────

def find_scc() -> Optional[str]:
    env = os.environ.get("SCC_BIN")
    if env and Path(env).is_file():
        return env
    on_path = shutil.which("scc")
    if on_path:
        return on_path
    for base in (Path.cwd(), *Path.cwd().parents, HERE, *HERE.parents):
        for candidate in (base / ".tools/bin/scc", base / ".tools/scc"):
            if candidate.is_file():
                return str(candidate)
    return None


def find_jscpd() -> Tuple[Optional[List[str]], str]:
    """Return (command prefix, engine label) for running jscpd."""
    direct = shutil.which("jscpd")
    if direct:
        return [direct], "jscpd"
    npx = shutil.which("npx")
    if npx:
        probe = run([npx, "--yes", "jscpd", "--version"], timeout=180)
        if probe.ok:
            return [npx, "--yes", "jscpd"], "jscpd-npx"
    return None, "builtin-fallback"


def docker_available() -> bool:
    if not shutil.which("docker"):
        return False
    return run(["docker", "info", "--format", "{{.ServerVersion}}"], timeout=20).ok


# ── repo list parsing ────────────────────────────────────────────────────────

class RepoSpec:
    __slots__ = ("raw", "platform", "full_name", "clone_url", "local_path", "name")

    def __init__(self, raw: str, platform: str, full_name: str,
                 clone_url: Optional[str], local_path: Optional[Path]):
        self.raw = raw
        self.platform = platform
        self.full_name = full_name
        self.clone_url = clone_url
        self.local_path = local_path
        self.name = full_name.replace("/", "__") or (local_path.name if local_path else "repo")


def parse_repo_entry(raw: str, default_platform: str = "github",
                     gitlab_host: str = "gitlab.com",
                     base_dir: Optional[Path] = None) -> Optional[RepoSpec]:
    entry = raw.strip()
    if not entry or entry.startswith("#"):
        return None
    # Listing exports often annotate each line, e.g. "group/repo  [private]".
    entry = re.sub(r"\s*\[[^\]]*\]\s*$", "", entry).strip()
    entry = re.sub(r"\s{2,}.*$", "", entry).strip()
    if not entry:
        return None

    expanded = Path(os.path.expanduser(entry))
    if not (expanded.exists() and expanded.is_dir()) and not expanded.is_absolute() and base_dir is not None:
        # A relative local path is checked against cwd first (unchanged
        # behavior); if that misses, also try it relative to the repo-list
        # file's own directory, so a bare sibling-folder entry (e.g. a repo
        # checked out next to repos.txt) resolves the same regardless of
        # the caller's cwd -- not just when run from repos.txt's directory.
        candidate = base_dir / entry
        if candidate.exists() and candidate.is_dir():
            expanded = candidate
    if expanded.exists() and expanded.is_dir():
        # Bare mirrors are named "<repo>.git"; drop the suffix so output rows and
        # clone directories read as the repository name.
        display = expanded.name[:-4] if expanded.name.endswith(".git") else expanded.name
        return RepoSpec(entry, "local", display, None, expanded.resolve())

    scp = re.match(r"^(?:ssh://)?git@([^:/]+)[:/](.+?)(?:\.git)?/?$", entry)
    if scp:
        host, path = scp.group(1), scp.group(2)
        platform = ("gitlab" if "gitlab" in host.lower() else
                    "github" if "github" in host.lower() else
                    "bitbucket" if "bitbucket" in host.lower() else "git")
        return RepoSpec(entry, platform, path, f"https://{host}/{path}.git", None)

    url = re.match(r"^https?://([^/]+)/(.+?)(?:\.git)?/?$", entry)
    if url:
        host, path = url.group(1), url.group(2)
        path = re.sub(r"/-/tree/.*$|/tree/.*$", "", path)
        path = re.sub(r"^([\w.-]+/[\w.-]+)/src/.*$", r"\1", path) if "bitbucket" in host.lower() else path
        platform = ("gitlab" if "gitlab" in host.lower() else
                    "github" if "github" in host.lower() else
                    "bitbucket" if "bitbucket" in host.lower() else "git")
        return RepoSpec(entry, platform, path, f"https://{host}/{path}.git", None)

    if re.match(r"^[\w.-]+(/[\w.-]+)+$", entry):
        if default_platform == "gitlab":
            return RepoSpec(entry, "gitlab", entry, f"https://{gitlab_host}/{entry}.git", None)
        return RepoSpec(entry, "github", entry, f"https://github.com/{entry}.git", None)

    return None


def load_repo_list(path: Path, default_platform: str = "github",
                   gitlab_host: str = "gitlab.com") -> List[RepoSpec]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    specs: List[RepoSpec] = []
    seen = set()
    base_dir = path.resolve().parent

    def add(raw: Any) -> None:
        if not raw:
            return
        spec = parse_repo_entry(str(raw), default_platform, gitlab_host, base_dir=base_dir)
        if spec and spec.full_name not in seen:
            seen.add(spec.full_name)
            specs.append(spec)

    suffix = path.suffix.lower()
    if suffix == ".jsonl":
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            add(_first_key(obj, ("clone_url", "repo_url", "url", "html_url", "full_name", "path")))
    elif suffix == ".json":
        data = json.loads(text or "[]")
        items = data if isinstance(data, list) else data.get("repos", [])
        for obj in items:
            if isinstance(obj, str):
                add(obj)
            elif isinstance(obj, dict):
                add(_first_key(obj, ("clone_url", "repo_url", "url", "html_url", "full_name", "path")))
    elif suffix == ".csv":
        for row in csv.DictReader(text.splitlines()):
            add(_first_key(row, ("clone_url", "repo_url", "url", "html_url", "full_name", "path", "repo")))
    else:
        for line in text.splitlines():
            add(line)

    return specs


def _first_key(obj: Dict[str, Any], keys: Sequence[str]) -> Optional[str]:
    for key in keys:
        value = obj.get(key)
        if value:
            return str(value)
    return None


# ── auth / cloning ───────────────────────────────────────────────────────────

def load_tokens(tokens_file: Optional[Path]) -> Dict[str, str]:
    tokens: Dict[str, str] = {}
    for env_key, slot in (
        ("GH_TOKEN", "github"), ("GITHUB_TOKEN", "github"),
        ("GITLAB_TOKEN", "gitlab"), ("CI_JOB_TOKEN", "gitlab"),
        ("BITBUCKET_ACCOUNT_SCOPED_TOKEN", "bitbucket"), ("BITBUCKET_TOKEN", "bitbucket"),
    ):
        value = os.environ.get(env_key)
        if value and slot not in tokens:
            tokens[slot] = value
    if tokens_file and tokens_file.is_file():
        for line in tokens_file.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key, value = key.strip().lower(), value.strip().strip('"').strip("'")
            if not value:
                continue
            if "github" in key and "github" not in tokens:
                tokens["github"] = value
            elif "gitlab" in key and "gitlab" not in tokens:
                tokens["gitlab"] = value
            elif "bitbucket" in key and "bitbucket" not in tokens:
                tokens["bitbucket"] = value
    return tokens


def authed_url(clone_url: str, platform: str, tokens: Dict[str, str]) -> str:
    token = tokens.get(platform)
    if not token or not clone_url.startswith("https://"):
        return clone_url
    rest = clone_url[len("https://"):]
    user = "oauth2" if platform == "gitlab" else "x-token-auth" if platform == "bitbucket" else "x-access-token"
    return f"https://{user}:{token}@{rest}"


def redact(text: str, tokens: Dict[str, str]) -> str:
    for token in tokens.values():
        if token:
            text = text.replace(token, "***")
    return text


def ensure_clone(spec: RepoSpec, clones_dir: Path, tokens: Dict[str, str],
                 timeout: int, blobless: bool,
                 allow_non_git: bool = False,
                 all_branches: bool = False) -> Tuple[Optional[Path], str]:
    """Return (path to a git working tree, note). Local repos are used in place."""
    if spec.local_path:
        if (spec.local_path / ".git").exists():
            return spec.local_path, "local"

        probe = run(["git", "rev-parse", "--is-bare-repository"], spec.local_path, 60)
        if probe.ok and probe.out.strip() == "true":
            # scc and jscpd need real files, which a bare mirror has none of, so
            # materialise a working tree beside the other clones.
            dest = clones_dir / "bare" / spec.name
            if (dest / ".git").exists():
                return dest, "cached worktree"
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.rmtree(dest, ignore_errors=True)
            result = run(["git", "clone", str(spec.local_path), str(dest)], timeout=timeout)
            if result.ok and (dest / ".git").exists():
                return dest, "materialised from bare mirror"
            shutil.rmtree(dest, ignore_errors=True)
            return None, f"clone from bare mirror failed: {result.tail(300)}"

        if allow_non_git:
            # Zip-derived source exports carry no history. LOC, duplication and
            # build detection still work; commit metrics are reported as blank
            # rather than zero, so absence is never mistaken for a real count.
            return spec.local_path, "non-git source tree"

        return None, "not a git repository"

    dest = clones_dir / spec.platform / spec.name
    if (dest / ".git").exists():
        return dest, "cached clone"

    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)

    url = authed_url(spec.clone_url or "", spec.platform, tokens)
    env = dict(os.environ, GIT_TERMINAL_PROMPT="0", GIT_ASKPASS="echo")

    # --single-branch fetches only the default branch, which makes
    # --branch-mode latest a no-op. Fetch every branch when the caller needs to
    # choose between them.
    scope: List[str] = [] if all_branches else ["--single-branch"]

    attempts: List[List[str]] = []
    if blobless:
        attempts.append(["git", "clone", "--filter=blob:none", *scope, url, str(dest)])
    attempts.append(["git", "clone", *scope, url, str(dest)])

    last = ""
    for cmd in attempts:
        result = run(cmd, timeout=timeout, env=env)
        if result.ok and (dest / ".git").exists():
            return dest, "cloned"
        last = redact(result.tail(300), tokens)
        shutil.rmtree(dest, ignore_errors=True)
    return None, f"clone failed: {last}"


# ── branch selection ─────────────────────────────────────────────────────────

def branch_file_count(repo: Path, branch: str) -> int:
    """Tracked file count on a branch, without checking it out."""
    result = run(["git", "ls-tree", "-r", "--name-only", branch], repo, 300)
    if not result.ok:
        return -1
    return sum(1 for line in result.out.splitlines() if line.strip())


def resolve_branch(repo: Path, mode: str) -> Tuple[str, str]:
    """Return (branch to measure, default branch).

    `latest` picks the newest commit, which fails when a trivial commit lands on
    an otherwise empty branch. `largest` picks the branch carrying the most
    tracked files, which is what "where the code lives" usually means.
    """
    default = ""
    ref = run(["git", "symbolic-ref", "refs/remotes/origin/HEAD"], repo, 60)
    if ref.ok:
        default = ref.out.strip().split("/")[-1]
    if not default:
        head = run(["git", "rev-parse", "--abbrev-ref", "HEAD"], repo, 60)
        default = head.out.strip() if head.ok else "HEAD"

    if mode not in ("latest", "largest"):
        return default, default

    listing = run(
        ["git", "for-each-ref", "--sort=-committerdate", "--format=%(refname:short)%09%(committerdate:unix)",
         "refs/remotes/origin", "refs/heads"],
        repo, 120,
    )
    if mode == "largest" and listing.ok:
        best, best_n = default, branch_file_count(repo, default)
        seen = 0
        for line in listing.out.splitlines():
            name = line.split("\t")[0].strip()
            if not name or name.endswith("/HEAD"):
                continue
            seen += 1
            if seen > 60:          # bound the cost on repos with hundreds of branches
                break
            n = branch_file_count(repo, name)
            if n > best_n:
                best, best_n = name, n
        return best, default

    if listing.ok:
        for line in listing.out.splitlines():
            name = line.split("\t")[0].strip()
            if not name or name.endswith("/HEAD"):
                continue
            return name, default
    return default, default


# ── metric 1 + 2: scc ────────────────────────────────────────────────────────

def scc_code_total(scc_bin: str, repo: Path, extra: Optional[Sequence[str]] = None,
                   timeout: int = 900) -> Tuple[int, int, Dict[str, int]]:
    """Return (code lines, file count, {language: code lines})."""
    cmd = [scc_bin, "--format", "json"] + list(extra or []) + [str(repo)]
    result = run(cmd, timeout=timeout)
    if not result.ok:
        raise RuntimeError(f"scc failed: {result.tail(400)}")
    rows = json.loads(result.out or "[]")
    if not isinstance(rows, list):
        rows = []
    code = files = 0
    by_lang: Dict[str, int] = {}
    for row in rows:
        row_code = int(row.get("Code") or 0)
        code += row_code
        files += int(row.get("Count") or 0)
        name = row.get("Name") or "Unknown"
        by_lang[name] = by_lang.get(name, 0) + row_code
    return code, files, by_lang


def collect_loc(scc_bin: str, repo: Path, exclude_dirs: Sequence[str],
                timeout: int, data_languages: Optional[Sequence[str]] = None) -> Dict[str, Any]:
    """Metrics 1 and 2, plus the intermediate figures that justify metric 2.

    `logical_loc` is the spec figure: scc's summed Code column over the whole
    repo, with no filtering whatsoever. `code_loc` is an additional, additive
    column that removes data/markup languages; it never alters `logical_loc`.
    """
    data_langs = set(data_languages) if data_languages is not None else DATA_LANGUAGES
    exclude_args: List[str] = []
    for name in exclude_dirs:
        exclude_args += ["--exclude-dir", name]

    total_code, total_files, by_lang = scc_code_total(scc_bin, repo, None, timeout)
    vendor_filtered, _, _ = scc_code_total(scc_bin, repo, exclude_args, timeout)
    authored, authored_files, authored_by_lang = scc_code_total(
        scc_bin, repo, exclude_args + ["--no-gen", "--no-min-gen"], timeout
    )

    primary = ""
    if authored_by_lang:
        primary = max(authored_by_lang.items(), key=lambda kv: kv[1])[0]
    elif by_lang:
        primary = max(by_lang.items(), key=lambda kv: kv[1])[0]

    ranked = sorted(authored_by_lang.items(), key=lambda kv: kv[1], reverse=True)[:6]
    denom = sum(authored_by_lang.values()) or 1
    breakdown = "; ".join(f"{name}:{100.0 * loc / denom:.1f}%" for name, loc in ranked if loc)

    code_only = {name: loc for name, loc in by_lang.items() if name not in data_langs and loc}
    code_loc = sum(code_only.values())
    data_loc = total_code - code_loc
    # `primary_language` can read "XML" on a repo that is 99% sitemap dumps, which
    # is useless on a vendor form; this reports the largest real source language.
    primary_code = max(code_only.items(), key=lambda kv: kv[1])[0] if code_only else ""
    ranked_data = sorted(
        ((name, loc) for name, loc in by_lang.items() if name in data_langs and loc),
        key=lambda kv: kv[1], reverse=True,
    )[:3]

    return {
        "logical_loc": total_code,
        "code_loc": code_loc,
        "data_loc": data_loc,
        "primary_code_language": primary_code,
        "code_loc_pct": round(100.0 * code_loc / total_code, 2) if total_code else 0.0,
        "top_data_languages": "; ".join(f"{name}:{loc}" for name, loc in ranked_data),
        "authored_loc": authored,
        "non_authored_loc": max(total_code - authored, 0),
        "non_authored_pct": round(100.0 * (total_code - authored) / total_code, 2) if total_code else 0.0,
        "vendored_loc": max(total_code - vendor_filtered, 0),
        "generated_minified_loc": max(vendor_filtered - authored, 0),
        "total_files": total_files,
        "authored_files": authored_files,
        "primary_language": primary,
        "language_breakdown": breakdown,
        "scc_exclude_dirs": ",".join(exclude_dirs),
    }


# ── metric 3: duplication ────────────────────────────────────────────────────

def union_duplicated_lines(duplicates: List[Dict[str, Any]]) -> int:
    """Count distinct source lines covered by at least one clone.

    Each jscpd duplicate names two fragments; a line can appear in many, so the
    ranges are merged per file before counting.
    """
    per_file: Dict[str, List[Tuple[int, int]]] = {}
    for dup in duplicates:
        for side in ("firstFile", "secondFile"):
            info = dup.get(side) or {}
            name = info.get("name")
            start, end = info.get("start"), info.get("end")
            if not name or start is None or end is None:
                continue
            lo, hi = int(start), int(end)
            if hi < lo:
                lo, hi = hi, lo
            per_file.setdefault(name, []).append((lo, hi))

    counted = 0
    for spans in per_file.values():
        spans.sort()
        cur_lo, cur_hi = spans[0]
        for lo, hi in spans[1:]:
            if lo <= cur_hi + 1:
                cur_hi = max(cur_hi, hi)
            else:
                counted += cur_hi - cur_lo + 1
                cur_lo, cur_hi = lo, hi
        counted += cur_hi - cur_lo + 1
    return counted


def jscpd_ratio(jscpd_cmd: List[str], repo: Path, report_dir: Path,
                exclude_dirs: Sequence[str], min_tokens: int, min_lines: int,
                timeout: int, gitignore: bool = True) -> Dict[str, Any]:
    report_dir.mkdir(parents=True, exist_ok=True)
    names = list(dict.fromkeys(list(exclude_dirs) + sorted(ALWAYS_SKIP_DIRS)))
    ignore = ",".join(f"**/{name}/**" for name in names)
    cmd = jscpd_cmd + [
        str(repo),
        "--min-tokens", str(min_tokens),
        "--min-lines", str(min_lines),
        "--reporters", "json",
        "--output", str(report_dir),
        "--ignore", ignore,
    ]
    if not gitignore:
        # jscpd 5 honours .gitignore by default, which is what we want: scc does
        # too, so both metrics then cover the same file set.
        cmd.append("--no-gitignore")
    result = run(cmd, timeout=timeout)
    report = report_dir / "jscpd-report.json"
    if not report.is_file():
        raise RuntimeError(f"no jscpd report: {result.tail(400)}")
    data = json.loads(report.read_text(encoding="utf-8", errors="ignore") or "{}")
    total = ((data.get("statistics") or {}).get("total") or {})
    percentage = float(total.get("percentage") or 0.0)
    total_lines = int(total.get("lines") or 0)

    # jscpd's `percentage` sums each clone's line count, so a line belonging to
    # several clone pairs is counted once per pair and the figure can exceed
    # 100%. Recompute from the union of duplicated line ranges: the fraction of
    # distinct lines appearing in at least one clone. That is what a duplication
    # ratio means, and it cannot exceed 1.
    unique_lines = union_duplicated_lines(data.get("duplicates") or [])
    if total_lines and unique_lines:
        ratio = min(unique_lines / total_lines, 1.0)
        method = "union-of-clone-ranges"
    else:
        ratio = min(percentage / 100.0, 1.0)
        method = "jscpd-percentage"

    return {
        "duplication_ratio": round(ratio, 4),
        "duplication_pct": round(ratio * 100, 2),
        "duplication_pct_jscpd_raw": round(percentage, 2),
        "duplication_unique_lines": unique_lines,
        "duplication_method": method,
        "duplication_overlapping": percentage > 100.0,
        "duplicated_lines": int(total.get("duplicatedLines") or 0),
        "duplication_scanned_lines": int(total.get("lines") or 0),
        "duplication_clones": int(total.get("clones") or 0),
        "duplication_command": " ".join(cmd),
    }


def is_autogen(path: Path, rel: str) -> bool:
    name = rel.split("/")[-1]
    lower = name.lower()
    for pattern in AUTOGEN_FILE_PATTERNS:
        if fnmatch.fnmatch(lower, pattern.lower()):
            return True
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            head = "".join(handle.readline() for _ in range(5)).lower()
    except OSError:
        return False
    return any(marker in head for marker in AUTOGEN_HEADER_MARKERS)


def walk_source_files(repo: Path, exclude_dirs: Sequence[str], limit: int) -> List[Tuple[Path, str]]:
    """Tracked source files only, so the scan matches scc's .gitignore-aware view."""
    skip = {name.lower() for name in exclude_dirs} | {n.lower() for n in ALWAYS_SKIP_DIRS}
    found: List[Tuple[Path, str]] = []

    def accept(rel: str) -> bool:
        parts = {p.lower() for p in rel.split("/")[:-1] if p}
        return not (parts & skip) and Path(rel).suffix.lower() in SOURCE_EXTENSIONS

    listing = run(["git", "ls-files", "-z"], repo, 300)
    if listing.ok:
        for rel in listing.out.split("\0"):
            rel = rel.strip()
            if not rel or not accept(rel):
                continue
            path = repo / rel
            if path.is_file():
                found.append((path, rel))
                if len(found) >= limit:
                    break
        return found

    for root, dirs, filenames in os.walk(repo):
        dirs[:] = [d for d in dirs if d.lower() not in skip]
        for filename in filenames:
            path = Path(root) / filename
            rel = path.relative_to(repo).as_posix()
            if not accept(rel):
                continue
            found.append((path, rel))
            if len(found) >= limit:
                return found
    return found


def builtin_dup_ratio(repo: Path, exclude_dirs: Sequence[str], min_tokens: int,
                      min_lines: int, file_limit: int) -> Dict[str, Any]:
    """Fallback duplication estimate: sliding window of normalised code lines.

    Same window parameters as the jscpd invocation, but a different algorithm —
    rows produced this way are labelled `builtin-fallback` and are not
    interchangeable with jscpd output.
    """
    candidates = walk_source_files(repo, exclude_dirs, file_limit)
    seen: Counter = Counter()
    total_windows = 0
    scanned_lines = 0
    for path, rel in candidates:
        if is_autogen(path, rel):
            continue
        try:
            lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        except OSError:
            continue
        code_lines = []
        for line in lines:
            stripped = line.strip()
            if not stripped or stripped.startswith(("//", "#", "*", "/*")):
                continue
            code_lines.append(stripped)
        scanned_lines += len(code_lines)
        if len(code_lines) < min_lines:
            continue
        for index in range(len(code_lines) - min_lines + 1):
            block = "\n".join(code_lines[index:index + min_lines])
            if len(re.findall(r"\w+", block)) < min_tokens:
                continue
            total_windows += 1
            seen[block] += 1
    duplicate_windows = sum(count - 1 for count in seen.values() if count > 1)
    ratio = round(min(duplicate_windows / total_windows, 1.0), 4) if total_windows else 0.0
    return {
        "duplication_ratio": ratio,
        "duplication_pct": round(ratio * 100, 2),
        "duplicated_lines": duplicate_windows,
        "duplication_scanned_lines": scanned_lines,
        "duplication_clones": sum(1 for count in seen.values() if count > 1),
        "duplication_command": f"builtin window={min_lines} min_tokens={min_tokens}",
    }


# ── metric 4: commits ────────────────────────────────────────────────────────

REVERT_RE = re.compile(r"\brevert\b", re.IGNORECASE)


def non_merge_commits(repo: Path, branch: str, timeout: int) -> Dict[str, Any]:
    result = run(["git", "log", branch, "--no-merges", "--pretty=format:%s"], repo, timeout)
    if not result.ok:
        result = run(["git", "log", "--no-merges", "--pretty=format:%s"], repo, timeout)
        if not result.ok:
            raise RuntimeError(f"git log failed: {result.tail(300)}")
    subjects = result.out.splitlines()
    reverts = sum(1 for line in subjects if REVERT_RE.search(line))

    first = run(["git", "log", branch, "--reverse", "--pretty=format:%aI", "--max-parents=0"], repo, timeout)
    last = run(["git", "log", branch, "-1", "--pretty=format:%aI"], repo, timeout)
    authors = run(["git", "shortlog", "-sne", "--no-merges", branch], repo, timeout)

    return {
        "non_merge_commits": len(subjects) - reverts,
        "non_merge_commits_raw": len(subjects),
        "revert_commits_excluded": reverts,
        "contributors": len([ln for ln in authors.out.splitlines() if ln.strip()]) if authors.ok else "",
        "first_commit": (first.out.splitlines() or [""])[0].strip() if first.ok else "",
        "last_commit": last.out.strip() if last.ok else "",
    }


# ── metric 5: builds and tests ───────────────────────────────────────────────

class BuildPlan:
    __slots__ = ("system", "build_cmd", "test_cmd", "runtime", "runtime_source", "image")

    def __init__(self, system: str, build_cmd: str, test_cmd: str,
                 runtime: str, runtime_source: str, image: str):
        self.system = system
        self.build_cmd = build_cmd
        self.test_cmd = test_cmd
        self.runtime = runtime
        self.runtime_source = runtime_source
        self.image = image


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _json(path: Path) -> Dict[str, Any]:
    try:
        data = json.loads(_read(path) or "{}")
        return data if isinstance(data, dict) else {}
    except json.JSONDecodeError:
        return {}


# Which build system belongs to which source language, so a PHP app carrying a
# package.json for its frontend assets is not reported as a Node project.
LANGUAGE_BUILD_SYSTEMS = {
    "PHP": "php",
    "JavaScript": "node", "TypeScript": "node", "Vue": "node", "JSX": "node", "TSX": "node",
    "Python": "python",
    "Go": "go",
    "Java": "maven", "Kotlin": "gradle",
    "Ruby": "ruby",
    "C#": "dotnet",
    "Rust": "cargo",
}


def detect_build_plans(repo: Path) -> List[BuildPlan]:
    """Every build system present, most specific first."""
    plans: List[BuildPlan] = []
    for detector in (
        _plan_node, _plan_php, _plan_python, _plan_go, _plan_maven, _plan_gradle,
        _plan_ruby, _plan_cargo, _plan_dotnet, _plan_make, _plan_dockerfile,
    ):
        try:
            plan = detector(repo)
        except Exception:  # noqa: BLE001 - a bad manifest must not kill the repo
            plan = None
        if plan:
            plans.append(plan)
    return plans


def detect_build_plan(repo: Path, primary_language: str = "") -> Optional[BuildPlan]:
    """Pick the build system matching the repo's primary source language.

    Falls back to detection order when the primary language has no build system
    or that system is not present in the repo.
    """
    plans = detect_build_plans(repo)
    if not plans:
        return None
    preferred = LANGUAGE_BUILD_SYSTEMS.get(primary_language)
    if preferred:
        for plan in plans:
            if plan.system == preferred:
                return plan
    return plans[0]


def _plan_node(repo: Path) -> Optional[BuildPlan]:
    pkg = repo / "package.json"
    if pkg.is_file():
        data = _json(pkg)
        scripts = data.get("scripts") or {}
        runtime, source = "", ""
        nvmrc = repo / ".nvmrc"
        if nvmrc.is_file():
            runtime, source = _read(nvmrc).strip().lstrip("v"), ".nvmrc"
        elif (data.get("engines") or {}).get("node"):
            runtime, source = str(data["engines"]["node"]).strip(), "package.json engines.node"
        install = "npm ci" if (repo / "package-lock.json").is_file() else "npm install"
        if (repo / "yarn.lock").is_file():
            install = "yarn install --frozen-lockfile"
        elif (repo / "pnpm-lock.yaml").is_file():
            install = "pnpm install --frozen-lockfile"
        build = f"{install} && npm run build" if "build" in scripts else install
        test = "npm test" if "test" in scripts else ""
        major = re.sub(r"[^0-9.].*$", "", runtime).split(".")[0] or "20"
        return BuildPlan("node", build, test, runtime, source, f"node:{major}")
    return None


def _plan_go(repo: Path) -> Optional[BuildPlan]:
    if (repo / "go.mod").is_file():
        version = ""
        match = re.search(r"^go\s+([0-9.]+)", _read(repo / "go.mod"), re.M)
        if match:
            version = match.group(1)
        return BuildPlan("go", "go build ./...", "go test ./...", version, "go.mod",
                         f"golang:{version or '1.22'}")
    return None


def _plan_maven(repo: Path) -> Optional[BuildPlan]:
    if (repo / "pom.xml").is_file():
        version = ""
        text = _read(repo / "pom.xml")
        match = re.search(r"<maven\.compiler\.(?:release|source|target)>([^<]+)<", text)
        if match:
            version = match.group(1).strip()
        return BuildPlan("maven", "mvn -B -DskipTests package", "mvn -B test", version,
                         "pom.xml maven.compiler", f"maven:3-eclipse-temurin-{version or '17'}")
    return None


def _plan_gradle(repo: Path) -> Optional[BuildPlan]:
    if (repo / "build.gradle").is_file() or (repo / "build.gradle.kts").is_file():
        version = ""
        match = re.search(r"sourceCompatibility\s*=\s*['\"]?([0-9._]+)", _read(repo / "build.gradle"))
        if match:
            version = match.group(1)
        return BuildPlan("gradle", "gradle build -x test", "gradle test", version,
                         "build.gradle sourceCompatibility", f"gradle:jdk{(version or '17').split('.')[-1]}")
    return None


def _plan_python(repo: Path) -> Optional[BuildPlan]:
    if (repo / "pyproject.toml").is_file() or (repo / "requirements.txt").is_file() or (repo / "setup.py").is_file():
        version, source = "", ""
        pyver = repo / ".python-version"
        if pyver.is_file():
            version, source = _read(pyver).strip(), ".python-version"
        else:
            match = re.search(r'requires-python\s*=\s*["\']([^"\']+)', _read(repo / "pyproject.toml"))
            if match:
                version, source = match.group(1).strip(), "pyproject.toml requires-python"
        install = "pip install -r requirements.txt" if (repo / "requirements.txt").is_file() else "pip install ."
        major = re.sub(r"[^0-9.]", "", version)[:4].rstrip(".") or "3.11"
        return BuildPlan("python", install, "pytest -q", version, source, f"python:{major}")
    return None


def _plan_ruby(repo: Path) -> Optional[BuildPlan]:
    if (repo / "Gemfile").is_file():
        version, source = "", ""
        ruby_version = repo / ".ruby-version"
        if ruby_version.is_file():
            version, source = _read(ruby_version).strip(), ".ruby-version"
        else:
            match = re.search(r"ruby\s+['\"]([^'\"]+)", _read(repo / "Gemfile"))
            if match:
                version, source = match.group(1), "Gemfile ruby"
        test = "bundle exec rspec" if (repo / "spec").is_dir() else "bundle exec rake test"
        return BuildPlan("ruby", "bundle install", test, version, source,
                         f"ruby:{version or '3.2'}")
    return None


def _plan_php(repo: Path) -> Optional[BuildPlan]:
    if (repo / "composer.json").is_file():
        data = _json(repo / "composer.json")
        version = str((data.get("require") or {}).get("php") or "").strip()
        return BuildPlan("php", "composer install --no-interaction --no-progress",
                         "vendor/bin/phpunit", version, "composer.json require.php",
                         "composer:2")
    return None


def _plan_cargo(repo: Path) -> Optional[BuildPlan]:
    if (repo / "Cargo.toml").is_file():
        match = re.search(r'rust-version\s*=\s*["\']([^"\']+)', _read(repo / "Cargo.toml"))
        version = match.group(1) if match else ""
        return BuildPlan("cargo", "cargo build --locked", "cargo test", version,
                         "Cargo.toml rust-version", f"rust:{version or '1'}")
    return None


def _plan_dotnet(repo: Path) -> Optional[BuildPlan]:
    csproj = list(repo.glob("*.csproj")) + list(repo.glob("**/*.csproj"))[:1]
    if csproj or (repo / "global.json").is_file():
        version = str((_json(repo / "global.json").get("sdk") or {}).get("version") or "")
        major = version.split(".")[0] or "8.0"
        return BuildPlan("dotnet", "dotnet build -c Release", "dotnet test", version,
                         "global.json sdk.version", f"mcr.microsoft.com/dotnet/sdk:{major}")
    return None


def _plan_make(repo: Path) -> Optional[BuildPlan]:
    if (repo / "Makefile").is_file():
        text = _read(repo / "Makefile")
        return BuildPlan("make", "make", "make test" if re.search(r"^test:", text, re.M) else "",
                         "", "", "")
    return None


def _plan_dockerfile(repo: Path) -> Optional[BuildPlan]:
    if (repo / "Dockerfile").is_file():
        return BuildPlan("docker", "docker build .", "", "", "Dockerfile FROM", "")
    return None


def ci_runs_tests(repo: Path) -> bool:
    candidates: List[Path] = []
    workflows = repo / ".github/workflows"
    if workflows.is_dir():
        candidates += [p for p in workflows.iterdir() if p.suffix in {".yml", ".yaml"}]
    for name in (".gitlab-ci.yml", "Jenkinsfile", ".circleci/config.yml", "azure-pipelines.yml"):
        path = repo / name
        if path.is_file():
            candidates.append(path)
    pattern = re.compile(r"\b(npm test|yarn test|pytest|go test|mvn .*test|gradle test|rspec|phpunit|dotnet test|cargo test|jest|tox|make test)\b", re.I)
    return any(pattern.search(_read(path)) for path in candidates)


def docker_build_test(repo: Path, plan: BuildPlan, timeout: int) -> Dict[str, Any]:
    """Attempt a real build and test run inside a language-matched container."""
    if not plan.image:
        if plan.system == "docker":
            result = run(["docker", "build", "-q", "."], repo, timeout)
            return {
                "build_test_status": "Builds only" if result.ok else "Not verified",
                "build_ok": result.ok,
                "test_ok": "",
                "build_log_tail": result.tail(600),
            }
        return {"build_test_status": "Not verified", "build_ok": "", "test_ok": "",
                "build_log_tail": "no container recipe for this build system"}

    mount = f"{repo}:/src"
    base = ["docker", "run", "--rm", "-v", mount, "-w", "/src", plan.image, "sh", "-lc"]

    build = run(base + [plan.build_cmd], timeout=timeout)
    if not build.ok:
        return {"build_test_status": "Not verified", "build_ok": False, "test_ok": "",
                "build_log_tail": build.tail(600)}
    if not plan.test_cmd:
        return {"build_test_status": "Builds only", "build_ok": True, "test_ok": "",
                "build_log_tail": "no test command detected"}

    test = run(base + [f"{plan.build_cmd} && {plan.test_cmd}"], timeout=timeout)
    return {
        "build_test_status": "Builds + test suite passes" if test.ok else "Builds only",
        "build_ok": True,
        "test_ok": test.ok,
        "build_log_tail": test.tail(600),
    }


def find_dockerfiles(repo: Path, limit: int = 50) -> List[str]:
    """Dockerfiles at any depth, not just the repo root.

    Monorepos and service repos routinely keep them under docker/, deploy/ or
    per-service subdirectories, so a root-only check reports 'no Dockerfile'
    for repos that are fully containerised.
    """
    found: List[str] = []
    listing = run(["git", "ls-files", "-z"], repo, 300)
    if listing.ok:
        for rel in listing.out.split("\0"):
            rel = rel.strip()
            if rel and re.search(r"(^|/)Dockerfile", rel, re.I):
                found.append(rel)
                if len(found) >= limit:
                    break
        return found
    skip = {n.lower() for n in ALWAYS_SKIP_DIRS}
    for root, dirs, files in os.walk(repo):
        dirs[:] = [d for d in dirs if d.lower() not in skip]
        for name in files:
            if re.match(r"Dockerfile", name, re.I):
                found.append((Path(root) / name).relative_to(repo).as_posix())
                if len(found) >= limit:
                    return found
    return found


def collect_build_test(repo: Path, mode: str, timeout: int,
                       primary_language: str = "") -> Dict[str, Any]:
    dockerfiles = find_dockerfiles(repo)
    all_plans = detect_build_plans(repo)
    plan = detect_build_plan(repo, primary_language)
    row: Dict[str, Any] = {
        "build_systems_detected": ",".join(p.system for p in all_plans),
        "build_system": plan.system if plan else "unknown",
        "build_command": plan.build_cmd if plan else "",
        "test_command": plan.test_cmd if plan else "",
        "runtime_version": plan.runtime if plan else "",
        "runtime_version_source": plan.runtime_source if plan else "",
        "container_image": plan.image if plan else "",
        "dockerfile_present": bool(dockerfiles),
        "dockerfile_count": len(dockerfiles),
        "dockerfile_paths": ";".join(dockerfiles[:5]),
        "ci_runs_tests": ci_runs_tests(repo),
        "build_test_status": "Not verified",
        "build_ok": "",
        "test_ok": "",
        "build_log_tail": "",
        "build_check_mode": mode,
    }
    if mode == "docker" and plan:
        try:
            row.update(docker_build_test(repo, plan, timeout))
        except Exception as exc:  # noqa: BLE001 - one repo must not kill the run
            row["build_log_tail"] = f"{type(exc).__name__}: {exc}"
    return row


# ── per-repo driver ──────────────────────────────────────────────────────────

CSV_COLUMNS = [
    "repo", "platform", "source", "source_kind", "analysis_branch", "default_branch",
    "logical_loc", "non_authored_loc", "non_authored_pct", "authored_loc",
    "vendored_loc", "generated_minified_loc",
    "code_loc", "data_loc", "code_loc_pct", "primary_code_language", "top_data_languages",
    "duplication_ratio", "duplication_pct", "duplication_pct_jscpd_raw", "duplication_method", "duplication_engine",
    "non_merge_commits", "revert_commits_excluded", "non_merge_commits_raw",
    "build_test_status", "build_system", "build_systems_detected", "build_command", "test_command",
    "runtime_version", "runtime_version_source", "ci_runs_tests", "dockerfile_present", "dockerfile_count",
    "primary_language", "language_breakdown", "total_files", "authored_files",
    "contributors", "first_commit", "last_commit",
    "duplication_scanned_lines", "duplication_clones", "duplicated_lines",
    "measurement_seconds", "status", "error",
]


def process_repo(spec: RepoSpec, cfg: argparse.Namespace, scc_bin: str,
                 jscpd_cmd: Optional[List[str]], dup_engine: str,
                 tokens: Dict[str, str], out_dir: Path) -> Dict[str, Any]:
    started = time.time()
    artifact = out_dir / "artifacts" / f"{spec.name}.json"
    row: Dict[str, Any] = {
        "repo": spec.full_name,
        "platform": spec.platform,
        "source": spec.raw,
        "status": "ok",
        "error": "",
        "duplication_engine": dup_engine,
    }

    clone_path = None
    cloned_fresh = False
    try:
        clone_path, note = ensure_clone(
            spec, Path(cfg.clones_dir), tokens, cfg.clone_timeout, not cfg.full_clone,
            cfg.allow_non_git, cfg.branch_mode in ("latest", "largest"),
        )
        if clone_path is None:
            raise RuntimeError(note)
        cloned_fresh = note == "cloned"
        has_git = note != "non-git source tree"
        row["source_kind"] = "git" if has_git else "source-export"

        branch = ""
        if has_git:
            branch, default = resolve_branch(clone_path, cfg.branch_mode)
            row["analysis_branch"] = branch
            row["default_branch"] = default
            if cfg.branch_mode in ("latest", "largest") and branch != default:
                run(["git", "checkout", "--force", branch], clone_path, 600)

        row.update(collect_loc(scc_bin, clone_path, cfg.exclude_dirs, cfg.scc_timeout,
                               cfg.data_languages))

        if jscpd_cmd:
            try:
                row.update(jscpd_ratio(
                    jscpd_cmd, clone_path, out_dir / "jscpd" / spec.name,
                    cfg.exclude_dirs, cfg.min_tokens, cfg.min_lines, cfg.jscpd_timeout,
                    not cfg.no_gitignore,
                ))
            except Exception as exc:  # noqa: BLE001 - fall back rather than lose the repo
                row.update(builtin_dup_ratio(clone_path, cfg.exclude_dirs, cfg.min_tokens,
                                             cfg.min_lines, cfg.dup_file_limit))
                row["duplication_engine"] = "builtin-fallback"
                row["error"] = f"jscpd fell back: {exc}"
        else:
            row.update(builtin_dup_ratio(clone_path, cfg.exclude_dirs, cfg.min_tokens,
                                         cfg.min_lines, cfg.dup_file_limit))

        if has_git:
            row.update(non_merge_commits(clone_path, branch, cfg.git_timeout))
        else:
            # Blank, not 0 — there is no history to count, which is different
            # from a repository that genuinely has no commits.
            row.update({
                "non_merge_commits": "", "non_merge_commits_raw": "",
                "revert_commits_excluded": "", "contributors": "",
                "first_commit": "", "last_commit": "",
            })
        row.update(collect_build_test(clone_path, cfg.build_check, cfg.build_timeout,
                                      str(row.get("primary_code_language") or "")))

    except Exception as exc:  # noqa: BLE001 - record and continue with the next repo
        row["status"] = "error"
        row["error"] = redact(f"{type(exc).__name__}: {exc}", tokens)
        if cfg.traceback:
            log(traceback.format_exc())
    finally:
        if cfg.delete_clones and cloned_fresh and clone_path and not spec.local_path:
            shutil.rmtree(clone_path, ignore_errors=True)

    row["measurement_seconds"] = round(time.time() - started, 1)
    artifact.parent.mkdir(parents=True, exist_ok=True)
    artifact.write_text(json.dumps(row, indent=2, default=str), encoding="utf-8")
    return row


# ── output ───────────────────────────────────────────────────────────────────

def write_outputs(rows: List[Dict[str, Any]], out_dir: Path) -> None:
    rows = sorted(rows, key=lambda r: str(r.get("repo") or ""))
    csv_path = out_dir / "repo_metrics.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in CSV_COLUMNS})

    with (out_dir / "repo_metrics.jsonl").open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, default=str) + "\n")

    ok = [r for r in rows if r.get("status") == "ok"]
    failed = [r for r in rows if r.get("status") != "ok"]
    engines = Counter(r.get("duplication_engine") for r in ok)
    statuses = Counter(r.get("build_test_status") for r in ok)
    summary = {
        "repos_total": len(rows),
        "repos_ok": len(ok),
        "repos_failed": len(failed),
        "logical_loc_total": sum(int(r.get("logical_loc") or 0) for r in ok),
        "non_authored_loc_total": sum(int(r.get("non_authored_loc") or 0) for r in ok),
        "duplication_ratio_mean": round(
            sum(float(r.get("duplication_ratio") or 0) for r in ok) / len(ok), 4) if ok else 0.0,
        "non_merge_commits_total": sum(int(r.get("non_merge_commits") or 0) for r in ok),
        "duplication_engines": dict(engines),
        "build_test_status_counts": dict(statuses),
        "failures": [{"repo": r.get("repo"), "error": r.get("error")} for r in failed],
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    log(f"wrote {csv_path}")
    log(f"ok={len(ok)} failed={len(failed)} "
        f"logical_loc={summary['logical_loc_total']:,} "
        f"non_authored_loc={summary['non_authored_loc_total']:,}")


# ── cli ──────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repos", required=True, type=Path,
                        help="file listing repos (txt/csv/json/jsonl)")
    parser.add_argument("--out", required=True, type=Path, help="output directory")
    parser.add_argument("--clones-dir", default=default_clones_dir(),
                        help="where remote repos are cloned (env: DATALABS_CLONES_DIR)")
    parser.add_argument("--tokens-file", type=Path, default=default_tokens_file(),
                        help="key=value file with GitHub/GitLab tokens (env: DATALABS_TOKENS)")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--limit", type=int, default=0, help="process at most N repos")
    parser.add_argument("--branch-mode", choices=["default", "latest", "largest"], default="default")
    parser.add_argument("--default-platform", choices=["github", "gitlab"], default="github",
                        help="platform assumed for bare owner/repo lines")
    parser.add_argument("--gitlab-host", default="gitlab.com",
                        help="host used for bare gitlab paths, e.g. gitlab.mycorp.com")
    parser.add_argument("--build-check", choices=["none", "detect", "docker"], default="detect",
                        help="detect = static build/runtime identification; docker = real build+test attempt")
    parser.add_argument("--exclude-dirs", default=",".join(DEFAULT_EXCLUDE_DIRS))
    parser.add_argument("--data-languages", default=",".join(sorted(DATA_LANGUAGES)),
                        help="languages treated as data when deriving code_loc; "
                             "logical_loc is never affected")
    parser.add_argument("--wide-exclude", action="store_true",
                        help="also exclude third_party, Pods, target, .next and similar")
    parser.add_argument("--min-tokens", type=int, default=50)
    parser.add_argument("--min-lines", type=int, default=5)
    parser.add_argument("--dup-file-limit", type=int, default=8000,
                        help="max files scanned by the built-in duplication fallback")
    parser.add_argument("--no-jscpd", action="store_true",
                        help="skip jscpd and always use the built-in detector")
    parser.add_argument("--no-gitignore", action="store_true",
                        help="let the duplication scan see gitignored files (scc never does)")
    parser.add_argument("--allow-non-git", action="store_true",
                        help="measure source trees with no git history; commit "
                             "metrics are left blank rather than reported as zero")
    parser.add_argument("--full-clone", action="store_true",
                        help="disable --filter=blob:none partial clones")
    parser.add_argument("--delete-clones", action="store_true",
                        help="remove freshly cloned repos after measuring")
    parser.add_argument("--force", action="store_true",
                        help="re-measure repos that already have an artifact")
    parser.add_argument("--clone-timeout", type=int, default=1800)
    parser.add_argument("--scc-timeout", type=int, default=900)
    parser.add_argument("--jscpd-timeout", type=int, default=1800)
    parser.add_argument("--git-timeout", type=int, default=900)
    parser.add_argument("--build-timeout", type=int, default=2400)
    parser.add_argument("--traceback", action="store_true")
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    cfg = build_parser().parse_args(argv)

    cfg.exclude_dirs = [d.strip() for d in cfg.exclude_dirs.split(",") if d.strip()]
    cfg.data_languages = [d.strip() for d in cfg.data_languages.split(",") if d.strip()]
    if cfg.wide_exclude:
        cfg.exclude_dirs = list(dict.fromkeys(cfg.exclude_dirs + WIDE_EXTRA_EXCLUDE_DIRS))

    scc_bin = find_scc()
    if not scc_bin:
        log("ERROR: scc not found. Set SCC_BIN, or place it at .tools/bin/scc, or brew install scc")
        return 2

    jscpd_cmd: Optional[List[str]] = None
    dup_engine = "builtin-fallback"
    if not cfg.no_jscpd:
        jscpd_cmd, dup_engine = find_jscpd()
    if jscpd_cmd is None and not cfg.no_jscpd:
        log("WARNING: jscpd not found (needs Node). Falling back to the built-in detector; "
            "rows will be labelled duplication_engine=builtin-fallback and are NOT jscpd numbers.")

    if cfg.build_check == "docker" and not docker_available():
        log("WARNING: docker daemon unreachable — downgrading --build-check to detect")
        cfg.build_check = "detect"

    specs = load_repo_list(cfg.repos, cfg.default_platform, cfg.gitlab_host)
    if cfg.limit:
        specs = specs[:cfg.limit]
    if not specs:
        log(f"ERROR: no usable repo entries in {cfg.repos}")
        return 2

    out_dir: Path = resolve_out(cfg.out)
    (out_dir / "artifacts").mkdir(parents=True, exist_ok=True)
    Path(cfg.clones_dir).mkdir(parents=True, exist_ok=True)
    tokens = load_tokens(cfg.tokens_file)

    rows: List[Dict[str, Any]] = []
    pending: List[RepoSpec] = []
    for spec in specs:
        artifact = out_dir / "artifacts" / f"{spec.name}.json"
        if artifact.is_file() and not cfg.force:
            try:
                rows.append(json.loads(artifact.read_text(encoding="utf-8")))
                continue
            except json.JSONDecodeError:
                pass
        pending.append(spec)

    log(f"{len(specs)} repos | {len(rows)} cached | {len(pending)} to measure | "
        f"scc={scc_bin} duplication={dup_engine} build-check={cfg.build_check} "
        f"workers={cfg.workers}")

    done = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, cfg.workers)) as pool:
        futures = {
            pool.submit(process_repo, spec, cfg, scc_bin, jscpd_cmd, dup_engine, tokens, out_dir): spec
            for spec in pending
        }
        for future in concurrent.futures.as_completed(futures):
            spec = futures[future]
            done += 1
            try:
                row = future.result()
            except Exception as exc:  # noqa: BLE001 - never lose the whole run
                row = {"repo": spec.full_name, "platform": spec.platform, "source": spec.raw,
                       "status": "error", "error": f"{type(exc).__name__}: {exc}"}
            rows.append(row)
            flag = "OK " if row.get("status") == "ok" else "ERR"
            log(f"[{done}/{len(pending)}] {flag} {row.get('repo')} "
                f"loc={row.get('logical_loc', '-')} dup={row.get('duplication_ratio', '-')} "
                f"commits={row.get('non_merge_commits', '-')} "
                f"({row.get('measurement_seconds', '?')}s)")
            write_outputs(rows, out_dir)

    write_outputs(rows, out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
